language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - tools
  - build-tools-27.0.0
  - android-27

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_085edc5e696f_key -iv $encrypted_085edc5e696f_iv -in cs.jks.enc -out cs.jks -d

script:
  - "./gradlew assembleRelease"

deploy:
  provider: releases
  api_key:
    secure: V3Qvax6+f9LiZ+OBOu6ZutSvR1cBdykN/fRJBTp99F+O9rVeM9F0Ei/L5WhtHmol0XlCw7qtry5odyLjR8F8S3i48SNNAxxmN4XdJdimGF1p2KAtZR7pebpKYITYoQzj/tbkEgvdjXDbcm78k1FjB7nW1SNQQkPPDv3hHvYRU/tdazJ4nA8Z/qybmfWvt38qukwhZLfORGCwsayloy2Uq+EV0Tn1kzbgxoGdEu8JgjfoAnzc25ZOBvsSUmxS7P7CWmMy8SJpeZQ71qHL0ITP8RlbMPATBwyWF3Apg2aBue12zZE/DXj09ZcTjvkfaSebnRO4VYHFgBv5xUGmyDXCJnNCo1koSFYkRyasgWzj7TirTqD5zwIN2FjUEa0JfXwVyZ72FGFN+mZH98oakxn0AY4xLOLjcyD9oMBZVJ6CwoWq1vvvLupSeD5P0Wvz1ww0gW5Nd2yqeMWo2rfmwHSouq9HGByEUaiqRji6EWbmL6f60Oy0P6krMlglXIdOS7ovtWuAEnabX2CGK00Gj7gDugEuBzy5vKbHBs5gvBiAGZ5kWYU/Q/f0OR6eAoxMOSY3UuDMlanSIJs9OxN7n13itKIDtxc5mw8laL/mGfdR4AD58vpKc0Ua7mIwJCGAakQ0QyDBwnZ1oxtkaFw1Iunkpw7NSAYu5G8838WS1sQq0DM=
  file: app/build/outputs/apk/release/app-release.apk
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
